// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRUEbot.Data;

namespace TRUEbot.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20190212205850_MigratePlayerLocations")]
    partial class MigratePlayerLocations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("TRUEbot.Data.Models.Hit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompletedBy");

                    b.Property<DateTime?>("CompletedOn");

                    b.Property<string>("OrderedBy")
                        .IsRequired();

                    b.Property<DateTime>("OrderedOn");

                    b.Property<int>("PlayerId");

                    b.Property<string>("Reason");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Hits");
                });

            modelBuilder.Entity("TRUEbot.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedBy");

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Alliance");

                    b.Property<string>("Location");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedAlliance");

                    b.Property<string>("NormalizedLocation");

                    b.Property<string>("NormalizedName")
                        .IsRequired();

                    b.Property<int?>("SystemId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TRUEbot.Data.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Faction");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("TRUEbot.Data.Models.Hit", b =>
                {
                    b.HasOne("TRUEbot.Data.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TRUEbot.Data.Models.Player", b =>
                {
                    b.HasOne("TRUEbot.Data.Models.System", "System")
                        .WithMany("Players")
                        .HasForeignKey("SystemId");
                });
#pragma warning restore 612, 618
        }
    }
}
